version: "3.5"
services:
  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    hostname: database
    environment:
        - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10