version: "2.2"
services:
  api:
    build: .
    container_name: api
    ports:
      - "3333:3333"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=mysql
      - DB_NAME=database_development
      - DB_PASSWORD=root
      - DB_PORT=3306
      - DB_USER=root
      - NODE_ENV=development
      - SHOP_API_PORT=3333
  mysql:
    image: mysql
    hostname: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10